name: Crash MATLAB (expect 3 crashes on Linux and 3 normal errors on Windows)

on:
  # Trigger the workflow on push or pull request
  #push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 18 1 * *'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

env:
  MATLAB_RELEASE: latest

jobs:
  test:
    name: Crash MATLAB during MEX setup or mexification
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # MEX does not work on windows-latest yet
        crash_type: [default, setup, mex]
        crash_indicator : [true, false]
        exclude:
          - crash_type: default
            crash_indicator: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.2
        with:
          submodules: recursive

      - name: Miscellaneous setup
        run: bash .github/scripts/misc_setup

      - name: Link gfortran for MATLAB on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo bash .github/scripts/link_gfortran ${{ env.GFORTRAN_VERSION }}
          realpath "$(command -v gfortran)"

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.1.2
        with:
          release: ${{ env.MATLAB_RELEASE }}

      - name: Run script
        uses: matlab-actions/run-command@v2.1.1
        with:
          command: |
              cd('crash');
              if strcmpi('${{ matrix.crash_type }}', 'default')
                  if ${{ matrix.crash_indicator }}
                      crash;
                  end
              else
                  if ${{ matrix.crash_indicator }}
                      crash('${{ matrix.crash_type }}')
                  else
                      crash('${{ matrix.crash_type }}', false)
                  end
              end
