name: Illustrate an issue with Qt and MATLAB R2025a; expected to fail with "R2025a", "false", "false"
on:
  push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 16 * * 5'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  build:
    name: Illustrate an issue with Qt and MATLAB R2025a
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
        matlab: [R2024b, R2025a, latest]
        reinstall_packages: [true, false]  # Whether to re-install necessary packages removed by `free-disk-space`
        misc_setup: [true, false]  # Whether to run `mist_setup` after cloning the repository; this will also re-install necessary packages removed by `free-disk-space`


    steps:


      - name: Run `sudo apt update`
        run: sudo apt update  # Otherwise, free-disk-space or other actions relying on `apt` may fail

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # all of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false  # Important, or the runner may be shut down due to memory starvation.

      - name: Re-install necessary packages removed by `free-disk-space`
        if: ${{ matrix.reinstall_packages }}
        run: |
          # The following were removed by the `large-packages` section of `free-disk-space`.
          # Without them, MATLAB R2025a when running `plot` crashes with an internal error:
          # "Assertion: This application failed to start because no Qt platform plugin could be initialized".
          sudo apt install -y libgl1 libgl1-mesa-dri libglx-mesa0 libglx0 xvfb

      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      # Miscellaneous setup. This must be run AFTER `free-disk-space`, not before, as `free-disk-space`
      # may remove some packages that are installed by the miscellaneous setup.
      - name: Miscellaneous setup
        if: ${{ matrix.misc_setup }}
        run: bash .github/scripts/misc_setup

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.5.0
        with:
          release: ${{ matrix.matlab }}
          cache: true

      - name: Conduct the test
        uses: matlab-actions/run-command@v2
        with:
          command: |
            ver
            x = linspace(0, 1)
            plot(x, x)  % `plot` triggers the issue
