name: Illustrate an issue with Qt and MATLAB R2025a
on:
  push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 16 * * 5'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  build:
    name: Illustrate an issue with Qt and MATLAB R2025a
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
        matlab: [latest, R2025a]


    steps:


      - name: Run `sudo apt update`
        run: sudo apt update  # Otherwise, free-disk-space or other actions relying on `apt` may fail

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # all of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false  # Important, or the runner may be shut down due to memory starvation.

      - name: Install packages needed by MATLAB; they may have been removed by `free-disk-space`
        run: |
          sudo apt install -y libgl1 libgl1-mesa-dri libglx-mesa0 libglx0 xvfb

      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.5.0
        with:
          release: ${{ matrix.matlab }}
          cache: true

      - name: Conduct the test
        uses: matlab-actions/run-command@v2
        with:
          command: |
            ver; x = linspace(-2*pi,2*pi); y1 = sin(x); hfig = figure(); plot(x,y1); saveas(hfig, 'test', 'epsc2');
