name: Illustrate an issue of MATLAB with parfor; expected to fail with "profile"

on:
  #push:
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 16 * * 5'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:


jobs:
  build:
    name: Illustrate an issue of MATLAB with parfor
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        matlab: [R2021a, latest]
        test_name: [test, profile]


    steps:


      - name: Run `sudo apt update`
        run: sudo apt update  # Otherwise, free-disk-space or other actions relying on `apt` may fail

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # all of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false  # Important, or the runner may be shut down due to memory starvation.

      - name: Check out repository
        uses: actions/checkout@v5.0.0
        with:
          submodules: recursive

      # Miscellaneous setup. This must be run AFTER `free-disk-space`, not before, as `free-disk-space`
      # may remove some packages that are installed by the miscellaneous setup.
      - name: Miscellaneous setup
        if: ${{ matrix.misc_setup }}
        run: bash .github/scripts/misc_setup

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2.5.0
        with:
          release: ${{ matrix.matlab }}
          cache: true

      - name: Conduct the test
        uses: matlab-actions/run-command@v2
        with:
          command: |
            ver
            cd('test_parfor');
            if strcmp("${{ matrix.test_name }}", "test")
              disp('\nRunning test.m ...\n');
              test;
            else
              disp('\nRunning profile.m ...\n');
              profile;
            end
